from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.15.0")


##### setup report #####
configfile: "../config/config.yaml"


report: "../report/workflow.rst"


##### load rules #####
include: "rules/common.smk"
include: "rules/call_variants.smk"
include: "rules/call_variants_tumoronly.smk"
include: "rules/filter_results.smk"
include: "rules/annotation.smk"


##### target rules #####

rule all:
    input:
# CALL VARIANTS
        expand("results/{sample}_somatic_filtered_selected.vcf.gz",sample=list(samples_master.keys())),
# ANNOTATION
        expand("results/annotation/funcotator/{sample}_funcotated.maf",sample=list(samples_master.keys())),

