run:
  all: False
  call: False
  combine: False
  annotate: False
  analysis: False

# variant callers
callers:
  mutect: False
  lofreq: False
  varscan: False
  muse: False
  vardict: False
  strelka: False

# variant annotators
annotators:
  funcotator: False
  vep: False

variants:
  all: False

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.yaml

# reference files
resources:
  reference: /path/to/reference/reference_genome.fasta
  bed: /path/to/hg19.RefSeq.bed # hg38.RefSeq.bed
  dbsnp: /path/to/dbsnp.vcf.gz

params:
  gatk:
    Mutect: "--disable-read-filter MateOnSameContigOrNoMappedMateReadFilter --disable-read-filter NotDuplicateReadFilter --disable-read-filter NotSecondaryAlignmentReadFilter"
    SelectVariants: "--exclude-filtered --exclude-non-variants"
    Funcotator:
      resources: "/path/to/funcotator_resources"
      reference_version: "hg19" # options [hg19/hg38]
    germline: "/path/to/af-only-gnomad.vcf.gz"
    exac: "/path/to/small_exac_common_3.vcf.gz"
  vep:
    resources: "/path/to/vep_resources"
    reference_version: "hg19" # options [hg19/hg38]
    cache_version: "106"
  multiqc: "--force --interactive --cl_config 'max_table_rows: 700'"
  maftools:
    project_name: "musta"


paths:
  workdir: "/path/to/workdir"
  results_dir: "/path/to/results_dir"
  tmp_dir: "/path/to/tmp_dir"
  log_dir: "/path/to/log_dir"
  bench_dir: "/path/to/benchmark_dir"
  detection_folder_name: "detection"
  classification_folder_name: "classification"
  interpretation_folder_name: "interpretation"


