run:
  all: True
  call: False
  annotate: True
  profile: False

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)

samples: config/samples.yaml

# reference files
resources:
  reference: /path/to/reference/reference_genome.fasta
  bed: /path/to/bedfile/mybed.bed


params:
  gatk:
    Mutect: "--disable-read-filter MateOnSameContigOrNoMappedMateReadFilter --disable-read-filter NotDuplicateReadFilter --disable-read-filter NotSecondaryAlignmentReadFilter"
    SelectVariants: "--exclude-filtered --exclude-non-variants"
    Funcotator:
      resources: "/path/to/funcotator_resources"
      # options [hg19/hg38]
      reference_version: "hg19"
    germline: "/path/to/af-only-gnomad.vcf.gz"
    exac: "/path/to/small_exac_common_3.vcf.gz"
  multiqc: "--force --interactive --cl_config 'max_table_rows: 700'"


paths:
  workdir: "/path/to/workdir"
  project_name: "project_name"
  tmp_dir: "/path/to/tmp_dir"
