run:
  all: False
  call: False
  annotate: True
  profile: False

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)

samples: config/samples_vcf.yaml

# reference files
ref:
  species: homo_sapiens
  basepath: /path/to/reference_master_folder
  provider: ucsc
  release: hg19
  fasta: genome.fasta


params:
  gatk:
    Mutect: "--disable-read-filter MateOnSameContigOrNoMappedMateReadFilter --disable-read-filter NotDuplicateReadFilter --disable-read-filter NotSecondaryAlignmentReadFilter"
    SelectVariants: "--exclude-filtered --exclude-non-variants"
    Funcotator: "/path/to/funcotator_resources"
    germline: "/path/to/af-only-gnomad.vcf.gz"
    exac: "/path/to/small_exac_common_3.vcf.gz"
  multiqc: "--force --interactive --cl_config 'max_table_rows: 700'"


processing:
  interval_list: "/path/to/mybed.bed"
  tmp_dir: "/path/to/tmp_dir"
  base_tmp: "/tmp"
