sampleA:
  normal_bam:
    - ../test-data-somatic/data/bam/N1.chr22.bam
  tumor_bam:
    - ../test-data-somatic/data/bam/A25.chr22.bam
  vcf:
    - ../test-data-somatic/data/bam/N1.chr22.bam
sampleB:
  normal_bam:
  tumor_bam:
    - ../test-data-somatic/data/bam/B33.chr22.bam
  vcf:
    - ../test-data-somatic/data/bam/B33.chr22.bam
