patientA:
  normal_sample_name:
    - N1
  tumor_sample_name:
    - A25
  normal_bam:
    - test-data-somatic/data/bam/N1.chr22.bam
  tumor_bam:
    - test-data-somatic/data/bam/A25.chr22.bam
  vcf:
    - test-data-somatic/data/vcf/patientA_somatic_filtered_selected.vcf.gz

patientBRCA:
  maf:
    - test-data-somatic/data/maf/BRCA_subset_25_samples.maf
