$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:

  samples:
    type: string

  resources:
    type: object
    properties:
      reference:
        type: string
      bed:
        type: string
    required:
      - reference
      - bed

  paths:
    type: object
    properties:
      workdir:
        type: string
      results_dir:
        type: string
      tmp_dir:
        type: string
    required:
      - workdir
      - results_dir
      - tmp_dir

  params:
    type: object
    properties:
      gatk:
        type: object
        properties:
          Mutect:
            type: string
          SelectVariants:
            type: string
          Funcotator:
            type: object
            properties:
              resources:
                type: string
              reference_version:
                type: string
            required:
              - resources
              - reference_version
        required:
          - Mutect
          - SelectVariants
          - Funcotator
      multiqc:
        type: string
    required:
      - gatk
      - multiqc

required:
  - samples
  - resources
  - paths
  - params
